### ISSUE TITLE
Requirements for 1.0

### ISSUE THREAD

**Issue by sergiovilar** [alterfw/alter#13]
This version should implement these requirements:  

- [x] Hero as dependency 
- [x] Ampersand as dependency
- [x] options-page as dependency 
- [x] A CLI to wrap all these dependencies 
- [x] Alter must be a theme base for a project 
- [ ] Port the current website to a Couscous template
- [ ] Move documentation to the website
- [ ] Update documentation

**Comment by jpaulobneto** [comment]
Could you describe what updates are required in documentation?

**Comment by sergiovilar** [comment]
@jpaulobneto All of them! The current Alter's documentation is complete outdated with the changes for 1.x release. We need to join Ampersand's and Hero's documentation in a way that they can be read separated but also together, you know what I mean?

Let me explain a little bit:

Amepersand and Hero could me used without each other, Alter joins Ampersand, Hero and options-page into a single project, giving the developers a framework-based structure. That's why they should be read separately but also together. Won't be usefull maintain the current websites (Ampersand and Hero) and the Alter website with duplicated documentations.

**Comment by sergiovilar** [comment]
Closing here in favor of [alterfw/docs](http://github.com/alterfw/docs).
