### ISSUE TITLE
Meta-Box: javascript and stylesheet path problem

### ISSUE THREAD

**Issue by Giseudo** [alterfw/alter#14]
Sergio, o Alter, ao menos aqui, está tendo problemas em carregar o caminho correto para os **javascripts** e **stylesheets** do Meta-Box.

![captura de tela 2015-10-24 as 03 01 36](https://cloud.githubusercontent.com/assets/1698875/10709246/e446b9e6-79fb-11e5-9339-56f74b47ff72.png)

Isso acontece quando tento incluir campos do tipo "multiple images"… simplesmente ele não executa os scripts por que não encontra.

**Workaround:**
Troquei a linha 20 do arquivo "/alterfw/alter/src/main.php"
- De: define('RWMB_URL', ALTER_VENDOR . "/meta-box/" );
- Para: define('RWMB_URL', get_bloginfo('template_url') . "/vendor/alterfw/meta-box/" );

Obviamente essa não é uma solução bonita, e também não sei se esse erro rola por aí.

**Comment by sergiovilar** [comment]
@Giseudo tô ciente desse problema. O lance é que o Alter não está sendo mais desenvolvido nesse repositório, mas sim nesses dois:
https://github.com/alterfw/hero
https://github.com/alterfw/options-page

Tu pode simplesmente atualizar teu composer.json pra como está esse, a issue deve ser resolvida trocando o Alter por esses dois outros projetos:
https://github.com/alterfw/alter/blob/1.x-dev/composer.json
