### ISSUE TITLE
Class 'Route' not found

### ISSUE THREAD

**Issue by victorximenis** [alterfw/alter#16]
When I follow the steps in [Alter Docs](http://alterframework.com/docs/) I get an route error with the Route class.

`Fatal error: Class 'Route' not found in /var/www/html/wp-content/themes/my-theme/main.php on line 3`

It is easy to solve this problem by adding `use Ampersand\Route` in main.php file.

It would be good to include this instruction to the documentation.

**Comment by sergiovilar** [comment]
Thanks for reporting this bug @victorximenis.
