### ISSUE TITLE
Route only takes absolute path

### ISSUE THREAD

**Issue by blebon-km** [alterfw/alter#17]
If your wordpress is not located at the root of your webserver you must specify the absolute path in each routes which is, in my opinion, counterintuitive. The application should behave the same way whether it's located at the root or in a subfolder of the webserver !
Actually it took me time to understand why my routing wasn't working ! If you don't plan to fix it immediatly I think it could be nice to have a few words about it in the documentation ;)

**Comment by victorximenis** [comment]
Hi, @blebon-km.
If i understand correctly, you have two problems, right?
For the second, Alter uses [WordPress Rewrite API](https://codex.wordpress.org/Rewrite_API).
The Rewrite API needs .htaccess to work fine.
Try this:
`<IfModule mod_rewrite.c>`
`RewriteEngine On`
`RewriteBase /`
`RewriteRule ^index\.php$ - [L]`
`RewriteCond %{REQUEST_FILENAME} !-f`
`RewriteCond %{REQUEST_FILENAME} !-d`
`RewriteRule . /index.php [L]`
`</IfModule>`

If you are using docker, i think this is provided to you by default, but if you are not, try this solution.

For your first problem, can you give me more details about your environment?

**Comment by blebon-km** [comment]
Hello,

I think you misunderstood my "problem", so I'll explain with an example:
Let's consider that I have a wordpress located at the URL **http://localhost/my/subfolder/wordpress** in my developpement environment.
Now I'm adding a new Route:

```
Route::get('/hello', function(){
  echo "Hello !"
});
```

Then, when I type the URL **http://localhost/my/subfolder/wordpress/hello** I expect to see the message "Hello" but instead I get a 404 error.

To make it work, I need to change my code to replace the relative path with an absolute path like this:

```
Route::get('/my/subfolder/wordpress/hello', function(){
  echo "Hello !"
});
```

This can be annoying because in a production environnent the URL of my wordpress won't be the same so I'll have to change all my routes to make it work.

**Comment by sergiopvilar** [comment]
@blebon-km Thanks for reporting! This is a know problem actually, I'll give you a heads up when I do the fix. For now I advice you to create a subdomain to your subfolder installation, if it's possible. Sorry about that!

**Comment by sergiopvilar** [comment]
@blebon-km Alter is built on top of FastRoute, please take a look on [this issue](https://github.com/nikic/FastRoute/issues/71) and tell me if any of the solutions works.

**Comment by blebon-km** [comment]
Actually I took a look in the Ampersand project (the Route.php file) and I think the problem might be either located in the addRoute method around the line 134:

```
    $_route = $this->getPrefix($parameters[0]);
    $broken = array_values(array_filter(explode('/', $_route)));
    $robj = [];
    $robj['methods'] = $methods;
    $robj['callback'] = $parameters[count($parameters) -1];

    foreach($broken as $part){
      if(preg_match('/^:[a-zA-Z0-9]+/', $part))
        $_route = str_replace($part, "{".substr($part, 1)."}", $_route);
    }

    $robj['route'] = $_route;
```

The $_route variable contains a relative path so maybe we should turn it into an absolute path ?

or either in the parse_request method around the line 265:

```
    $httpMethod = $_SERVER['REQUEST_METHOD'];
    $uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

    if(strpos($uri, '/wp-admin') > -1) return;

    if($uri == '/404' || $uri == '/404/')
      http_response_code(404);

    $routeInfo = $dispatcher->dispatch($httpMethod, $uri);
```

At this moment the $uri variable contains the absolute path, so it won't match any route that has a relative path.

But I'm not sure if these are the right places to fix this "problem". What's your opinion about it ?

Anyway, there's also a workaround that consists in nesting all the routes in a Route::group that has the base URI of the application as a path which simplify a lot the transition between the development and the production environment.

**Comment by sergiopvilar** [comment]
@blebon-km sorry for the long delay! This should be fixed in Ampersand's latest release.
