### ISSUE TITLE
namespace for classes

### ISSUE THREAD

**Issue by vinicius73** [alterfw/alter#9]
Begin using the PSR-0 standard classes of Alter. 
http://www.php-fig.org/psr/psr-0/ 

Enhancing compatibility and avoiding conflicts of classes.

**Comment by sergiovilar** [comment]
Alter has turned into a theme base for his dependencies (see [Hero](https://github.com/alterfw/hero), [Ampersand](https://github.com/alterfw/ampersand) and [options-page](https://github.com/alterfw/ampersand)) and all of them follows PSR-4 when is possible. So, this issue doesn't make sense anymore.

Thank you anyway.
